# Check the documentation at http://goreleaser.com
project_name: CloudODM
builds:
  -
    main: ./cmd/odm/main.go
    binary: odm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: 386
archive:
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: Mac
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
